\timing on
\echo '\nPOI: Add aditioanl fields'

ALTER TABLE :scm.osm_point_poi ADD COLUMN lon float, ADD COLUMN lat float;
ALTER TABLE :scm.osm_polygon_poi ADD COLUMN lon float, ADD COLUMN lat float;
ALTER TABLE :scm.osm_linestring_poi ADD COLUMN lon float, ADD COLUMN lat float;

SELECT AddGeometryColumn('import', 'osm_polygon_poi', 'centre', 3857, 'POINT', 2);
SELECT AddGeometryColumn('import', 'osm_linestring_poi', 'centre', 3857, 'POINT', 2);

\echo '\nPOI: Prepare'
UPDATE :scm.osm_point_poi SET lon = ST_X(ST_Transform(geometry, 4326)), lat = ST_Y(ST_Transform(geometry, 4326));

UPDATE :scm.osm_polygon_poi SET
      centre = ST_PointOnSurface(geometry),
      lon = ST_X(ST_Transform(ST_PointOnSurface(geometry), 4326)),
      lat = ST_Y(ST_Transform(ST_PointOnSurface(geometry), 4326))
WHERE ST_IsValid(geometry);

UPDATE :scm.osm_linestring_poi SET
      centre = ST_PointOnSurface(geometry),
      lon = ST_X(ST_Transform(ST_PointOnSurface(geometry), 4326)),
      lat = ST_Y(ST_Transform(ST_PointOnSurface(geometry), 4326))
;

\echo '\nPOI: Combine'
CREATE VIEW import.osm_poi_view AS
SELECT row_number() OVER () id, * FROM (
SELECT u1.osm_id, name, name_uk, name_ru, name_pl, name_en, addr_housenumber, addr_street, addr_suburb, operator, phone, contact_phone, website, contact_website, email, contact_email, fax, contact_fax, wikipedia, opening_hours,
category_id,
geometry AS boundary, centre,
2 AS type, lat, lon
FROM
    (SELECT osm_id, array_agg(category_id) AS category_id FROM (
            SELECT osm_id, 35 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='bakery')
            UNION ALL SELECT osm_id, 36 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='books')
            UNION ALL SELECT osm_id, 37 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='alcohol')
            UNION ALL SELECT osm_id, 38 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='bicycle')
            UNION ALL SELECT osm_id, 39 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='convenience')
            UNION ALL SELECT osm_id, 40 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='mall')
            UNION ALL SELECT osm_id, 41 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='anime')
            UNION ALL SELECT osm_id, 42 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='antiques')
            UNION ALL SELECT osm_id, 43 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='art')
            UNION ALL SELECT osm_id, 44 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='bag')
            UNION ALL SELECT osm_id, 45 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='baby_goods')
            UNION ALL SELECT osm_id, 46 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='bathroom_furnishing')
            UNION ALL SELECT osm_id, 47 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='bed')
            UNION ALL SELECT osm_id, 48 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='boutique')
            UNION ALL SELECT osm_id, 49 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='beverages')
            UNION ALL SELECT osm_id, 50 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='butcher')
            UNION ALL SELECT osm_id, 51 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='carpet')
            UNION ALL SELECT osm_id, 52 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='charity')
            UNION ALL SELECT osm_id, 53 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='chemist')
            UNION ALL SELECT osm_id, 54 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='clothes')
            UNION ALL SELECT osm_id, 55 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='shoes')
            UNION ALL SELECT osm_id, 56 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='computer')
            UNION ALL SELECT osm_id, 57 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='copyshop')
            UNION ALL SELECT osm_id, 58 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='curtain')
            UNION ALL SELECT osm_id, 59 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='fabric')
            UNION ALL SELECT osm_id, 60 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='bedding')
            UNION ALL SELECT osm_id, 61 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='deli')
            UNION ALL SELECT osm_id, 62 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='dive')
            UNION ALL SELECT osm_id, 63 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='doityourself')
            UNION ALL SELECT osm_id, 64 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='erotic')
            UNION ALL SELECT osm_id, 65 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='farm')
            UNION ALL SELECT osm_id, 66 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='fishing')
            UNION ALL SELECT osm_id, 67 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='florist')
            UNION ALL SELECT osm_id, 68 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='frame')
            UNION ALL SELECT osm_id, 69 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='funeral_directors')
            UNION ALL SELECT osm_id, 70 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='furniture')
            UNION ALL SELECT osm_id, 71 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='garden_centre')
            UNION ALL SELECT osm_id, 72 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='gas')
            UNION ALL SELECT osm_id, 73 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='gift')
            UNION ALL SELECT osm_id, 74 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='glaziery')
            UNION ALL SELECT osm_id, 75 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='greengrocer')
            UNION ALL SELECT osm_id, 76 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='hardware')
            UNION ALL SELECT osm_id, 77 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='hearing_aids')
            UNION ALL SELECT osm_id, 78 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='herbalist')
            UNION ALL SELECT osm_id, 79 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='hifi')
            UNION ALL SELECT osm_id, 80 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='houseware')
            UNION ALL SELECT osm_id, 81 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='hunting')
            UNION ALL SELECT osm_id, 82 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='interior_decoration')
            UNION ALL SELECT osm_id, 83 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='jewelry')
            UNION ALL SELECT osm_id, 84 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='kiosk')
            UNION ALL SELECT osm_id, 85 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='kitchen')
            UNION ALL SELECT osm_id, 86 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='mobile_phone')
            UNION ALL SELECT osm_id, 87 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='motorcycle')
            UNION ALL SELECT osm_id, 88 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='musical_instrument')
            UNION ALL SELECT osm_id, 89 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='newsagent')
            UNION ALL SELECT osm_id, 90 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='optician')
            UNION ALL SELECT osm_id, 91 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='organic')
            UNION ALL SELECT osm_id, 92 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='outdoor')
            UNION ALL SELECT osm_id, 93 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='paint')
            UNION ALL SELECT osm_id, 94 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='pet')
            UNION ALL SELECT osm_id, 95 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='radiotechnics')
            UNION ALL SELECT osm_id, 96 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='seafood')
            UNION ALL SELECT osm_id, 97 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='second_hand')
            UNION ALL SELECT osm_id, 98 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='ship_chandler')
            UNION ALL SELECT osm_id, 99 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='sports')
            UNION ALL SELECT osm_id, 100 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='stationery')
            UNION ALL SELECT osm_id, 101 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='tableware')
            UNION ALL SELECT osm_id, 102 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='ticket')
            UNION ALL SELECT osm_id, 103 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='tobacco')
            UNION ALL SELECT osm_id, 104 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='toys')
            UNION ALL SELECT osm_id, 105 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='trade')
            UNION ALL SELECT osm_id, 106 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='vacuum_cleaner')
            UNION ALL SELECT osm_id, 107 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='variety_store')
            UNION ALL SELECT osm_id, 108 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='video')
            UNION ALL SELECT osm_id, 109 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='window_blind')
            UNION ALL SELECT osm_id, 110 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='confectionery')
            UNION ALL SELECT osm_id, 111 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='ice_cream')
            UNION ALL SELECT osm_id, 112 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='supermarket')
            UNION ALL SELECT osm_id, 113 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='department_store')
            UNION ALL SELECT osm_id, 114 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='electronics')
            UNION ALL SELECT osm_id, 115 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='car')
            UNION ALL SELECT osm_id, 116 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='car_parts')
            UNION ALL SELECT osm_id, 117 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='atv')
            UNION ALL SELECT osm_id, 118 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='pharmacy')
            UNION ALL SELECT osm_id, 119 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='hospital')
            UNION ALL SELECT osm_id, 120 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='doctors')
            UNION ALL SELECT osm_id, 121 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='clinic')
            UNION ALL SELECT osm_id, 122 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='dentist')
            UNION ALL SELECT osm_id, 123 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='nursing_home')
            UNION ALL SELECT osm_id, 124 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='social_facility')
            UNION ALL SELECT osm_id, 125 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='veterinary')
            UNION ALL SELECT osm_id, 126 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='mortuary')
            UNION ALL SELECT osm_id, 127 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='cafe')
            UNION ALL SELECT osm_id, 128 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='biergarten')
            UNION ALL SELECT osm_id, 129 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='restaurant')
            UNION ALL SELECT osm_id, 130 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='fast_food')
            UNION ALL SELECT osm_id, 131 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='bar')
            UNION ALL SELECT osm_id, 132 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='pub')
            UNION ALL SELECT osm_id, 133 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='food_court')
            UNION ALL SELECT osm_id, 134 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='bank')
            UNION ALL SELECT osm_id, 136 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='money_lender')
            UNION ALL SELECT osm_id, 137 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='pawnbroker')
            UNION ALL SELECT osm_id, 138 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='bureau_de_change')
            UNION ALL SELECT osm_id, 139 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='driving_school')
            UNION ALL SELECT osm_id, 140 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='computer')
            UNION ALL SELECT osm_id, 141 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='post_office')
            UNION ALL SELECT osm_id, 142 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='post_box')
            UNION ALL SELECT osm_id, 143 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='beauty')
            UNION ALL SELECT osm_id, 144 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='beauty' AND "beauty"='nails')
            UNION ALL SELECT osm_id, 145 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='hairdresser')
            UNION ALL SELECT osm_id, 146 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='massage')
            UNION ALL SELECT osm_id, 147 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='tattoo')
            UNION ALL SELECT osm_id, 148 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='dry_cleaning')
            UNION ALL SELECT osm_id, 149 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='laundry')
            UNION ALL SELECT osm_id, 150 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='car_rental')
            UNION ALL SELECT osm_id, 151 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='bicycle_rental')
            UNION ALL SELECT osm_id, 152 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='agricultural_engines')
            UNION ALL SELECT osm_id, 153 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='basket_maker')
            UNION ALL SELECT osm_id, 154 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='beekeeper')
            UNION ALL SELECT osm_id, 155 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='blacksmith')
            UNION ALL SELECT osm_id, 156 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='brewery')
            UNION ALL SELECT osm_id, 157 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='boatbuilder')
            UNION ALL SELECT osm_id, 158 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='bookbinder')
            UNION ALL SELECT osm_id, 159 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='carpenter')
            UNION ALL SELECT osm_id, 160 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='carpet_layer')
            UNION ALL SELECT osm_id, 161 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='caterer')
            UNION ALL SELECT osm_id, 162 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='clockmaker')
            UNION ALL SELECT osm_id, 163 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='dressmaker')
            UNION ALL SELECT osm_id, 164 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='electrician')
            UNION ALL SELECT osm_id, 165 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='gardener')
            UNION ALL SELECT osm_id, 166 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='glaziery')
            UNION ALL SELECT osm_id, 167 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='handicraft')
            UNION ALL SELECT osm_id, 168 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='hvac')
            UNION ALL SELECT osm_id, 169 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='insulation')
            UNION ALL SELECT osm_id, 170 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='jeweller')
            UNION ALL SELECT osm_id, 171 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='locksmith')
            UNION ALL SELECT osm_id, 172 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='key_cutter')
            UNION ALL SELECT osm_id, 173 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='metal_construction')
            UNION ALL SELECT osm_id, 174 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='optician')
            UNION ALL SELECT osm_id, 175 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='painter')
            UNION ALL SELECT osm_id, 176 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='parquet_layer')
            UNION ALL SELECT osm_id, 177 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='photographer')
            UNION ALL SELECT osm_id, 178 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='photographic_laboratory')
            UNION ALL SELECT osm_id, 179 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='plasterer')
            UNION ALL SELECT osm_id, 180 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='plumber')
            UNION ALL SELECT osm_id, 181 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='pottery')
            UNION ALL SELECT osm_id, 182 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='rigger')
            UNION ALL SELECT osm_id, 183 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='roofer')
            UNION ALL SELECT osm_id, 184 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='saddler')
            UNION ALL SELECT osm_id, 185 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='sailmaker')
            UNION ALL SELECT osm_id, 186 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='sawmill')
            UNION ALL SELECT osm_id, 187 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='scaffolder')
            UNION ALL SELECT osm_id, 188 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='sculptor')
            UNION ALL SELECT osm_id, 189 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='shoemaker')
            UNION ALL SELECT osm_id, 190 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='stand_builder')
            UNION ALL SELECT osm_id, 191 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='stonemason')
            UNION ALL SELECT osm_id, 192 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='sun_protection')
            UNION ALL SELECT osm_id, 193 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='sweep')
            UNION ALL SELECT osm_id, 194 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='tailor')
            UNION ALL SELECT osm_id, 195 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='tiler')
            UNION ALL SELECT osm_id, 196 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='tinsmith')
            UNION ALL SELECT osm_id, 197 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='upholsterer')
            UNION ALL SELECT osm_id, 198 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='watchmaker')
            UNION ALL SELECT osm_id, 199 AS category_id FROM :scm.osm_polygon_poi WHERE ("craft"='window_construction')
            UNION ALL SELECT osm_id, 200 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='bus_station')
            UNION ALL SELECT osm_id, 201 AS category_id FROM :scm.osm_polygon_poi WHERE ("railway"='subway_entrance')
            UNION ALL SELECT osm_id, 202 AS category_id FROM :scm.osm_polygon_poi WHERE ("railway"='station')
            UNION ALL SELECT osm_id, 203 AS category_id FROM :scm.osm_polygon_poi WHERE ("railway"='halt')
            UNION ALL SELECT osm_id, 204 AS category_id FROM :scm.osm_polygon_poi WHERE ("railway"='station' AND "station"='subway')
            UNION ALL SELECT osm_id, 205 AS category_id FROM :scm.osm_polygon_poi WHERE ("highway"='bus_stop')
            UNION ALL SELECT osm_id, 206 AS category_id FROM :scm.osm_polygon_poi WHERE ("railway"='tram_stop')
            UNION ALL SELECT osm_id, 207 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='taxi')
            UNION ALL SELECT osm_id, 208 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='car_repair')
            UNION ALL SELECT osm_id, 209 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='car_repair' AND "service"='tyres')
            UNION ALL SELECT osm_id, 210 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='vehicle_inspection')
            UNION ALL SELECT osm_id, 211 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='car_wash')
            UNION ALL SELECT osm_id, 212 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='fuel')
            UNION ALL SELECT osm_id, 213 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='charging_station')
            UNION ALL SELECT osm_id, 215 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='school')
            UNION ALL SELECT osm_id, 216 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='kindergarten')
            UNION ALL SELECT osm_id, 217 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='library')
            UNION ALL SELECT osm_id, 218 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='college')
            UNION ALL SELECT osm_id, 219 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='university')
            UNION ALL SELECT osm_id, 220 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='arts_centre')
            UNION ALL SELECT osm_id, 221 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='cinema')
            UNION ALL SELECT osm_id, 222 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='nightclub')
            UNION ALL SELECT osm_id, 223 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='community_centre')
            UNION ALL SELECT osm_id, 224 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='theatre')
            UNION ALL SELECT osm_id, 225 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='theatre' AND "theatre:genre"='circus')
            UNION ALL SELECT osm_id, 226 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='place_of_worship')
            UNION ALL SELECT osm_id, 227 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='place_of_worship' AND "religion"='christian')
            UNION ALL SELECT osm_id, 228 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='place_of_worship' AND "religion"='jewish')
            UNION ALL SELECT osm_id, 229 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='place_of_worship' AND "religion"='muslim')
            UNION ALL SELECT osm_id, 230 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='monastery')
            UNION ALL SELECT osm_id, 231 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='police')
            UNION ALL SELECT osm_id, 232 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='courthouse')
            UNION ALL SELECT osm_id, 233 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='prison')
            UNION ALL SELECT osm_id, 234 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='register_office')
            UNION ALL SELECT osm_id, 235 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='embassy')
            UNION ALL SELECT osm_id, 236 AS category_id FROM :scm.osm_polygon_poi WHERE ("leisure"='stadium')
            UNION ALL SELECT osm_id, 237 AS category_id FROM :scm.osm_polygon_poi WHERE ("leisure"='sports_centre')
            UNION ALL SELECT osm_id, 238 AS category_id FROM :scm.osm_polygon_poi WHERE ("tourism"='museum')
            UNION ALL SELECT osm_id, 239 AS category_id FROM :scm.osm_polygon_poi WHERE ("tourism"='attraction')
            UNION ALL SELECT osm_id, 240 AS category_id FROM :scm.osm_polygon_poi WHERE ("tourism"='information')
            UNION ALL SELECT osm_id, 241 AS category_id FROM :scm.osm_polygon_poi WHERE ("historic"='memorial')
            UNION ALL SELECT osm_id, 242 AS category_id FROM :scm.osm_polygon_poi WHERE ("tourism"='artwork')
            UNION ALL SELECT osm_id, 243 AS category_id FROM :scm.osm_polygon_poi WHERE ("historic"='archaeological_site')
            UNION ALL SELECT osm_id, 244 AS category_id FROM :scm.osm_polygon_poi WHERE ("historic"='battlefield')
            UNION ALL SELECT osm_id, 245 AS category_id FROM :scm.osm_polygon_poi WHERE ("historic"='boundary_stone')
            UNION ALL SELECT osm_id, 246 AS category_id FROM :scm.osm_polygon_poi WHERE ("historic"='castle')
            UNION ALL SELECT osm_id, 247 AS category_id FROM :scm.osm_polygon_poi WHERE ("historic"='city_gate')
            UNION ALL SELECT osm_id, 248 AS category_id FROM :scm.osm_polygon_poi WHERE ("historic"='fort')
            UNION ALL SELECT osm_id, 249 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='fountain')
            UNION ALL SELECT osm_id, 250 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='clock')
            UNION ALL SELECT osm_id, 251 AS category_id FROM :scm.osm_polygon_poi WHERE ("historic"='ruins')
            UNION ALL SELECT osm_id, 252 AS category_id FROM :scm.osm_polygon_poi WHERE ("historic"='rune_stone')
            UNION ALL SELECT osm_id, 253 AS category_id FROM :scm.osm_polygon_poi WHERE ("historic"='wreck')
            UNION ALL SELECT osm_id, 254 AS category_id FROM :scm.osm_polygon_poi WHERE ("historic"='ship')
            UNION ALL SELECT osm_id, 255 AS category_id FROM :scm.osm_polygon_poi WHERE ("historic"='monument')
            UNION ALL SELECT osm_id, 256 AS category_id FROM :scm.osm_polygon_poi WHERE ("tourism"='hotel')
            UNION ALL SELECT osm_id, 257 AS category_id FROM :scm.osm_polygon_poi WHERE ("tourism"='guest_house')
            UNION ALL SELECT osm_id, 258 AS category_id FROM :scm.osm_polygon_poi WHERE ("tourism"='hostel')
            UNION ALL SELECT osm_id, 259 AS category_id FROM :scm.osm_polygon_poi WHERE ("tourism"='motel')
            UNION ALL SELECT osm_id, 260 AS category_id FROM :scm.osm_polygon_poi WHERE ("office"='company')
            UNION ALL SELECT osm_id, 261 AS category_id FROM :scm.osm_polygon_poi WHERE ("office"='government')
            UNION ALL SELECT osm_id, 262 AS category_id FROM :scm.osm_polygon_poi WHERE ("office"='government' AND "government"='bailiff')
            UNION ALL SELECT osm_id, 263 AS category_id FROM :scm.osm_polygon_poi WHERE ("office"='government' AND "government"='prosecutor')
            UNION ALL SELECT osm_id, 264 AS category_id FROM :scm.osm_polygon_poi WHERE ("office"='government' AND "government"='pension_fund')
            UNION ALL SELECT osm_id, 265 AS category_id FROM :scm.osm_polygon_poi WHERE ("office"='government' AND "government"='migration')
            UNION ALL SELECT osm_id, 266 AS category_id FROM :scm.osm_polygon_poi WHERE ("office"='government' AND "government"='taxes')
            UNION ALL SELECT osm_id, 267 AS category_id FROM :scm.osm_polygon_poi WHERE ("office"='insurance')
            UNION ALL SELECT osm_id, 268 AS category_id FROM :scm.osm_polygon_poi WHERE ("office"='estate_agent')
            UNION ALL SELECT osm_id, 269 AS category_id FROM :scm.osm_polygon_poi WHERE ("office"='lawyer')
            UNION ALL SELECT osm_id, 270 AS category_id FROM :scm.osm_polygon_poi WHERE ("office"='lawyer' AND "lawyer"='notary')
            UNION ALL SELECT osm_id, 271 AS category_id FROM :scm.osm_polygon_poi WHERE ("office"='telecommunication')
            UNION ALL SELECT osm_id, 272 AS category_id FROM :scm.osm_polygon_poi WHERE ("office"='travel_agent')
            UNION ALL SELECT osm_id, 273 AS category_id FROM :scm.osm_polygon_poi WHERE ("office"='ngo')
            UNION ALL SELECT osm_id, 274 AS category_id FROM :scm.osm_polygon_poi WHERE ("office"='administrative')
            UNION ALL SELECT osm_id, 275 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='townhall')
            UNION ALL SELECT osm_id, 276 AS category_id FROM :scm.osm_polygon_poi WHERE ("office"='accountant')
            UNION ALL SELECT osm_id, 277 AS category_id FROM :scm.osm_polygon_poi WHERE ("office"='employment_agency')
            UNION ALL SELECT osm_id, 278 AS category_id FROM :scm.osm_polygon_poi WHERE ("office"='research')
            UNION ALL SELECT osm_id, 279 AS category_id FROM :scm.osm_polygon_poi WHERE ("office"='it')
            UNION ALL SELECT osm_id, 280 AS category_id FROM :scm.osm_polygon_poi WHERE ("office"='newspaper')
            UNION ALL SELECT osm_id, 281 AS category_id FROM :scm.osm_polygon_poi WHERE ("office"='architect')
            UNION ALL SELECT osm_id, 282 AS category_id FROM :scm.osm_polygon_poi WHERE ("office"='advertising_agency')
            UNION ALL SELECT osm_id, 283 AS category_id FROM :scm.osm_polygon_poi WHERE ("office"='educational_institution')
            UNION ALL SELECT osm_id, 284 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='studio')
            UNION ALL SELECT osm_id, 285 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='bookmaker')
            UNION ALL SELECT osm_id, 286 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='toilets')
            UNION ALL SELECT osm_id, 287 AS category_id FROM :scm.osm_polygon_poi WHERE ("tourism"='viewpoint')
            UNION ALL SELECT osm_id, 288 AS category_id FROM :scm.osm_polygon_poi WHERE ("tourism"='camp_site')
            UNION ALL SELECT osm_id, 289 AS category_id FROM :scm.osm_polygon_poi WHERE ("tourism"='picnic_site')
            UNION ALL SELECT osm_id, 290 AS category_id FROM :scm.osm_polygon_poi WHERE ("natural"='cave_entrance')
            UNION ALL SELECT osm_id, 292 AS category_id FROM :scm.osm_polygon_poi WHERE ("natural"='rock' OR "natural"='bare_rock' OR "natural"='cliff')
            UNION ALL SELECT osm_id, 296 AS category_id FROM :scm.osm_polygon_poi WHERE ("natural"='cape')
            UNION ALL SELECT osm_id, 297 AS category_id FROM :scm.osm_polygon_poi WHERE ("natural"='bay')
            UNION ALL SELECT osm_id, 298 AS category_id FROM :scm.osm_polygon_poi WHERE ("natural"='strait')
            UNION ALL SELECT osm_id, 299 AS category_id FROM :scm.osm_polygon_poi WHERE ("place"='island')
            UNION ALL SELECT osm_id, 300 AS category_id FROM :scm.osm_polygon_poi WHERE ("natural"='beach')
            UNION ALL SELECT osm_id, 301 AS category_id FROM :scm.osm_polygon_poi WHERE ("place"='islet')
            UNION ALL SELECT osm_id, 302 AS category_id FROM :scm.osm_polygon_poi WHERE ("leisure"='beach_resort')
            UNION ALL SELECT osm_id, 303 AS category_id FROM :scm.osm_polygon_poi WHERE ("leisure"='dance')
            UNION ALL SELECT osm_id, 304 AS category_id FROM :scm.osm_polygon_poi WHERE ("leisure"='dog_park')
            UNION ALL SELECT osm_id, 305 AS category_id FROM :scm.osm_polygon_poi WHERE ("leisure"='fishing')
            UNION ALL SELECT osm_id, 306 AS category_id FROM :scm.osm_polygon_poi WHERE ("leisure"='golf_course')
            UNION ALL SELECT osm_id, 307 AS category_id FROM :scm.osm_polygon_poi WHERE ("leisure"='ice_rink')
            UNION ALL SELECT osm_id, 308 AS category_id FROM :scm.osm_polygon_poi WHERE ("leisure"='marina')
            UNION ALL SELECT osm_id, 309 AS category_id FROM :scm.osm_polygon_poi WHERE ("leisure"='slipway')
            UNION ALL SELECT osm_id, 310 AS category_id FROM :scm.osm_polygon_poi WHERE ("leisure"='miniature_golf')
            UNION ALL SELECT osm_id, 311 AS category_id FROM :scm.osm_polygon_poi WHERE ("leisure"='pitch')
            UNION ALL SELECT osm_id, 312 AS category_id FROM :scm.osm_polygon_poi WHERE ("leisure"='track' AND "sport"='running')
            UNION ALL SELECT osm_id, 313 AS category_id FROM :scm.osm_polygon_poi WHERE ("leisure"='track' AND "sport"='cycling')
            UNION ALL SELECT osm_id, 314 AS category_id FROM :scm.osm_polygon_poi WHERE ("leisure"='track' AND "sport"='horse_racing')
            UNION ALL SELECT osm_id, 316 AS category_id FROM :scm.osm_polygon_poi WHERE ("leisure"='playground')
            UNION ALL SELECT osm_id, 317 AS category_id FROM :scm.osm_polygon_poi WHERE ("leisure"='swimming_pool')
            UNION ALL SELECT osm_id, 318 AS category_id FROM :scm.osm_polygon_poi WHERE ("leisure"='water_park')
            UNION ALL SELECT osm_id, 319 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='cosmetics')
            UNION ALL SELECT osm_id, 320 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='marketplace')
            UNION ALL SELECT osm_id, 321 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='telephone')
            UNION ALL SELECT osm_id, 322 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='ferry_terminal')
            UNION ALL SELECT osm_id, 323 AS category_id FROM :scm.osm_polygon_poi WHERE ("landuse"='cemetery')
            UNION ALL SELECT osm_id, 324 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='fire_station')
            UNION ALL SELECT osm_id, 325 AS category_id FROM :scm.osm_polygon_poi WHERE ("emergency"='phone')
            UNION ALL SELECT osm_id, 326 AS category_id FROM :scm.osm_polygon_poi WHERE ("emergency"='fire_hydrant')
            UNION ALL SELECT osm_id, 327 AS category_id FROM :scm.osm_polygon_poi WHERE ("emergency"='fire_water_pond')
            UNION ALL SELECT osm_id, 328 AS category_id FROM :scm.osm_polygon_poi WHERE ("emergency"='ambulance_station')
            UNION ALL SELECT osm_id, 329 AS category_id FROM :scm.osm_polygon_poi WHERE ("leisure"='park')
            UNION ALL SELECT osm_id, 330 AS category_id FROM :scm.osm_polygon_poi WHERE ("aeroway"='aerodrome')
            UNION ALL SELECT osm_id, 331 AS category_id FROM :scm.osm_polygon_poi WHERE ("aeroway"='helipad')
            UNION ALL SELECT osm_id, 332 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='shelter')
            UNION ALL SELECT osm_id, 334 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='sauna')
            UNION ALL SELECT osm_id, 335 AS category_id FROM :scm.osm_polygon_poi WHERE ("tourism"='zoo')
            UNION ALL SELECT osm_id, 336 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='parking')
            UNION ALL SELECT osm_id, 338 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='bicycle_parking')
            UNION ALL SELECT osm_id, 339 AS category_id FROM :scm.osm_polygon_poi WHERE ("tourism"='theme_park')
            UNION ALL SELECT osm_id, 340 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='customs')
            UNION ALL SELECT osm_id, 341 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='recycling')
            UNION ALL SELECT osm_id, 353 AS category_id FROM :scm.osm_polygon_poi WHERE ("man_made"='telephone_exchange')
            UNION ALL SELECT osm_id, 354 AS category_id FROM :scm.osm_polygon_poi WHERE ("man_made"='water_well')
            UNION ALL SELECT osm_id, 355 AS category_id FROM :scm.osm_polygon_poi WHERE ("man_made"='standpipe')
            UNION ALL SELECT osm_id, 356 AS category_id FROM :scm.osm_polygon_poi WHERE ("man_made"='water_works')
            UNION ALL SELECT osm_id, 357 AS category_id FROM :scm.osm_polygon_poi WHERE ("man_made"='wastewater_plant')
            UNION ALL SELECT osm_id, 358 AS category_id FROM :scm.osm_polygon_poi WHERE ("man_made"='water_tower')
            UNION ALL SELECT osm_id, 359 AS category_id FROM :scm.osm_polygon_poi WHERE ("power"='substation' OR "power"='station')
            UNION ALL SELECT osm_id, 360 AS category_id FROM :scm.osm_polygon_poi WHERE ("power"='transformer')
            UNION ALL SELECT osm_id, 361 AS category_id FROM :scm.osm_polygon_poi WHERE ("power"='plant' AND "plant:output:electricity"='*')
            UNION ALL SELECT osm_id, 362 AS category_id FROM :scm.osm_polygon_poi WHERE ("power"='generator' AND "generator:output:electricity"='*')
            UNION ALL SELECT osm_id, 363 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='sewing')
            UNION ALL SELECT osm_id, 366 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='internet_cafe')
            UNION ALL SELECT osm_id, 367 AS category_id FROM :scm.osm_polygon_poi WHERE ("club"='art')
            UNION ALL SELECT osm_id, 368 AS category_id FROM :scm.osm_polygon_poi WHERE ("club"='astronomy')
            UNION ALL SELECT osm_id, 369 AS category_id FROM :scm.osm_polygon_poi WHERE ("club"='computer')
            UNION ALL SELECT osm_id, 370 AS category_id FROM :scm.osm_polygon_poi WHERE ("club"='board_games')
            UNION ALL SELECT osm_id, 371 AS category_id FROM :scm.osm_polygon_poi WHERE ("club"='motorcycle')
            UNION ALL SELECT osm_id, 372 AS category_id FROM :scm.osm_polygon_poi WHERE ("club"='sport')
            UNION ALL SELECT osm_id, 373 AS category_id FROM :scm.osm_polygon_poi WHERE ("club"='game')
            UNION ALL SELECT osm_id, 374 AS category_id FROM :scm.osm_polygon_poi WHERE ("club"='automobile')
            UNION ALL SELECT osm_id, 375 AS category_id FROM :scm.osm_polygon_poi WHERE ("club"='chess')
            UNION ALL SELECT osm_id, 376 AS category_id FROM :scm.osm_polygon_poi WHERE ("club"='cinema')
            UNION ALL SELECT osm_id, 377 AS category_id FROM :scm.osm_polygon_poi WHERE ("club"='fan')
            UNION ALL SELECT osm_id, 378 AS category_id FROM :scm.osm_polygon_poi WHERE ("club"='fishing')
            UNION ALL SELECT osm_id, 379 AS category_id FROM :scm.osm_polygon_poi WHERE ("club"='veterans')
            UNION ALL SELECT osm_id, 380 AS category_id FROM :scm.osm_polygon_poi WHERE ("club"='linux')
            UNION ALL SELECT osm_id, 381 AS category_id FROM :scm.osm_polygon_poi WHERE ("club"='theatre')
            UNION ALL SELECT osm_id, 382 AS category_id FROM :scm.osm_polygon_poi WHERE ("club"='history')
            UNION ALL SELECT osm_id, 383 AS category_id FROM :scm.osm_polygon_poi WHERE ("club"='music')
            UNION ALL SELECT osm_id, 384 AS category_id FROM :scm.osm_polygon_poi WHERE ("club"='ethnic')
            UNION ALL SELECT osm_id, 385 AS category_id FROM :scm.osm_polygon_poi WHERE ("club"='nature')
            UNION ALL SELECT osm_id, 386 AS category_id FROM :scm.osm_polygon_poi WHERE ("club"='photography')
            UNION ALL SELECT osm_id, 387 AS category_id FROM :scm.osm_polygon_poi WHERE ("club"='hunting')
            UNION ALL SELECT osm_id, 388 AS category_id FROM :scm.osm_polygon_poi WHERE ("club"='shooting')
            UNION ALL SELECT osm_id, 389 AS category_id FROM :scm.osm_polygon_poi WHERE ("club"='tourism')
            UNION ALL SELECT osm_id, 390 AS category_id FROM :scm.osm_polygon_poi WHERE ("club"='charity')
            UNION ALL SELECT osm_id, 391 AS category_id FROM :scm.osm_polygon_poi WHERE ("man_made"='tunnel')
            UNION ALL SELECT osm_id, 392 AS category_id FROM :scm.osm_polygon_poi WHERE ("man_made"='bridge')
            UNION ALL SELECT osm_id, 393 AS category_id FROM :scm.osm_polygon_poi WHERE ("landuse"='construction')
            UNION ALL SELECT osm_id, 394 AS category_id FROM :scm.osm_polygon_poi WHERE ("landuse"='landfill')
            UNION ALL SELECT osm_id, 395 AS category_id FROM :scm.osm_polygon_poi WHERE ("amenity"='waste_disposal')
            UNION ALL SELECT osm_id, 396 AS category_id FROM :scm.osm_polygon_poi WHERE ("landuse"='garages')
            UNION ALL SELECT osm_id, 397 AS category_id FROM :scm.osm_polygon_poi WHERE ("man_made"='lighthouse')
            UNION ALL SELECT osm_id, 398 AS category_id FROM :scm.osm_polygon_poi WHERE ("highway"='speed_camera')
            UNION ALL SELECT osm_id, 399 AS category_id FROM :scm.osm_polygon_poi WHERE ("railway"='funicular')
            UNION ALL SELECT osm_id, 400 AS category_id FROM :scm.osm_polygon_poi WHERE ("shop"='tea')
            UNION ALL SELECT osm_id, 401 AS category_id FROM :scm.osm_polygon_poi WHERE ("advertising"='billboard')
            UNION ALL SELECT osm_id, 402 AS category_id FROM :scm.osm_polygon_poi WHERE ("advertising"='column')
            UNION ALL SELECT osm_id, 403 AS category_id FROM :scm.osm_polygon_poi WHERE ("advertising"='flag')
            UNION ALL SELECT osm_id, 404 AS category_id FROM :scm.osm_polygon_poi WHERE ("advertising"='sign')
          ) AS foo
    GROUP BY osm_id
    ) u1
    INNER JOIN :scm.osm_polygon_poi ON :scm.osm_polygon_poi.osm_id = u1.osm_id
    WHERE ST_IsValid(geometry)
UNION ALL
SELECT u2.osm_id, name, name_uk, name_ru, name_pl, name_en, addr_housenumber, addr_street, addr_suburb, operator, phone, contact_phone, website, contact_website, email, contact_email, fax, contact_fax, wikipedia, opening_hours,
category_id,
CAST(NULL AS geometry) AS boundary, geometry AS centre,
0 AS type, lat, lon
FROM
    (SELECT osm_id, array_agg(category_id) AS category_id FROM (
            SELECT osm_id, 35 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='bakery')
            UNION ALL SELECT osm_id, 36 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='books')
            UNION ALL SELECT osm_id, 37 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='alcohol')
            UNION ALL SELECT osm_id, 38 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='bicycle')
            UNION ALL SELECT osm_id, 39 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='convenience')
            UNION ALL SELECT osm_id, 40 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='mall')
            UNION ALL SELECT osm_id, 41 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='anime')
            UNION ALL SELECT osm_id, 42 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='antiques')
            UNION ALL SELECT osm_id, 43 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='art')
            UNION ALL SELECT osm_id, 44 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='bag')
            UNION ALL SELECT osm_id, 45 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='baby_goods')
            UNION ALL SELECT osm_id, 46 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='bathroom_furnishing')
            UNION ALL SELECT osm_id, 47 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='bed')
            UNION ALL SELECT osm_id, 48 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='boutique')
            UNION ALL SELECT osm_id, 49 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='beverages')
            UNION ALL SELECT osm_id, 50 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='butcher')
            UNION ALL SELECT osm_id, 51 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='carpet')
            UNION ALL SELECT osm_id, 52 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='charity')
            UNION ALL SELECT osm_id, 53 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='chemist')
            UNION ALL SELECT osm_id, 54 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='clothes')
            UNION ALL SELECT osm_id, 55 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='shoes')
            UNION ALL SELECT osm_id, 56 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='computer')
            UNION ALL SELECT osm_id, 57 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='copyshop')
            UNION ALL SELECT osm_id, 58 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='curtain')
            UNION ALL SELECT osm_id, 59 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='fabric')
            UNION ALL SELECT osm_id, 60 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='bedding')
            UNION ALL SELECT osm_id, 61 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='deli')
            UNION ALL SELECT osm_id, 62 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='dive')
            UNION ALL SELECT osm_id, 63 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='doityourself')
            UNION ALL SELECT osm_id, 64 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='erotic')
            UNION ALL SELECT osm_id, 65 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='farm')
            UNION ALL SELECT osm_id, 66 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='fishing')
            UNION ALL SELECT osm_id, 67 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='florist')
            UNION ALL SELECT osm_id, 68 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='frame')
            UNION ALL SELECT osm_id, 69 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='funeral_directors')
            UNION ALL SELECT osm_id, 70 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='furniture')
            UNION ALL SELECT osm_id, 71 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='garden_centre')
            UNION ALL SELECT osm_id, 72 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='gas')
            UNION ALL SELECT osm_id, 73 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='gift')
            UNION ALL SELECT osm_id, 74 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='glaziery')
            UNION ALL SELECT osm_id, 75 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='greengrocer')
            UNION ALL SELECT osm_id, 76 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='hardware')
            UNION ALL SELECT osm_id, 77 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='hearing_aids')
            UNION ALL SELECT osm_id, 78 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='herbalist')
            UNION ALL SELECT osm_id, 79 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='hifi')
            UNION ALL SELECT osm_id, 80 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='houseware')
            UNION ALL SELECT osm_id, 81 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='hunting')
            UNION ALL SELECT osm_id, 82 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='interior_decoration')
            UNION ALL SELECT osm_id, 83 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='jewelry')
            UNION ALL SELECT osm_id, 84 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='kiosk')
            UNION ALL SELECT osm_id, 85 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='kitchen')
            UNION ALL SELECT osm_id, 86 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='mobile_phone')
            UNION ALL SELECT osm_id, 87 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='motorcycle')
            UNION ALL SELECT osm_id, 88 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='musical_instrument')
            UNION ALL SELECT osm_id, 89 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='newsagent')
            UNION ALL SELECT osm_id, 90 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='optician')
            UNION ALL SELECT osm_id, 91 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='organic')
            UNION ALL SELECT osm_id, 92 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='outdoor')
            UNION ALL SELECT osm_id, 93 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='paint')
            UNION ALL SELECT osm_id, 94 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='pet')
            UNION ALL SELECT osm_id, 95 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='radiotechnics')
            UNION ALL SELECT osm_id, 96 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='seafood')
            UNION ALL SELECT osm_id, 97 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='second_hand')
            UNION ALL SELECT osm_id, 98 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='ship_chandler')
            UNION ALL SELECT osm_id, 99 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='sports')
            UNION ALL SELECT osm_id, 100 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='stationery')
            UNION ALL SELECT osm_id, 101 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='tableware')
            UNION ALL SELECT osm_id, 102 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='ticket')
            UNION ALL SELECT osm_id, 103 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='tobacco')
            UNION ALL SELECT osm_id, 104 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='toys')
            UNION ALL SELECT osm_id, 105 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='trade')
            UNION ALL SELECT osm_id, 106 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='vacuum_cleaner')
            UNION ALL SELECT osm_id, 107 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='variety_store')
            UNION ALL SELECT osm_id, 108 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='video')
            UNION ALL SELECT osm_id, 109 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='window_blind')
            UNION ALL SELECT osm_id, 110 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='confectionery')
            UNION ALL SELECT osm_id, 111 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='ice_cream')
            UNION ALL SELECT osm_id, 112 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='supermarket')
            UNION ALL SELECT osm_id, 113 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='department_store')
            UNION ALL SELECT osm_id, 114 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='electronics')
            UNION ALL SELECT osm_id, 115 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='car')
            UNION ALL SELECT osm_id, 116 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='car_parts')
            UNION ALL SELECT osm_id, 117 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='atv')
            UNION ALL SELECT osm_id, 118 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='pharmacy')
            UNION ALL SELECT osm_id, 119 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='hospital')
            UNION ALL SELECT osm_id, 120 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='doctors')
            UNION ALL SELECT osm_id, 121 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='clinic')
            UNION ALL SELECT osm_id, 122 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='dentist')
            UNION ALL SELECT osm_id, 123 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='nursing_home')
            UNION ALL SELECT osm_id, 124 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='social_facility')
            UNION ALL SELECT osm_id, 125 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='veterinary')
            UNION ALL SELECT osm_id, 126 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='mortuary')
            UNION ALL SELECT osm_id, 127 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='cafe')
            UNION ALL SELECT osm_id, 128 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='biergarten')
            UNION ALL SELECT osm_id, 129 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='restaurant')
            UNION ALL SELECT osm_id, 130 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='fast_food')
            UNION ALL SELECT osm_id, 131 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='bar')
            UNION ALL SELECT osm_id, 132 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='pub')
            UNION ALL SELECT osm_id, 133 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='food_court')
            UNION ALL SELECT osm_id, 134 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='bank')
            UNION ALL SELECT osm_id, 135 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='atm' OR "amenity"='bank' AND "atm"='yes')
            UNION ALL SELECT osm_id, 136 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='money_lender')
            UNION ALL SELECT osm_id, 137 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='pawnbroker')
            UNION ALL SELECT osm_id, 138 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='bureau_de_change')
            UNION ALL SELECT osm_id, 139 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='driving_school')
            UNION ALL SELECT osm_id, 140 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='computer')
            UNION ALL SELECT osm_id, 141 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='post_office')
            UNION ALL SELECT osm_id, 142 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='post_box')
            UNION ALL SELECT osm_id, 143 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='beauty')
            UNION ALL SELECT osm_id, 144 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='beauty' AND "beauty"='nails')
            UNION ALL SELECT osm_id, 145 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='hairdresser')
            UNION ALL SELECT osm_id, 146 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='massage')
            UNION ALL SELECT osm_id, 147 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='tattoo')
            UNION ALL SELECT osm_id, 148 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='dry_cleaning')
            UNION ALL SELECT osm_id, 149 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='laundry')
            UNION ALL SELECT osm_id, 150 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='car_rental')
            UNION ALL SELECT osm_id, 151 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='bicycle_rental')
            UNION ALL SELECT osm_id, 152 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='agricultural_engines')
            UNION ALL SELECT osm_id, 153 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='basket_maker')
            UNION ALL SELECT osm_id, 154 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='beekeeper')
            UNION ALL SELECT osm_id, 155 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='blacksmith')
            UNION ALL SELECT osm_id, 156 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='brewery')
            UNION ALL SELECT osm_id, 157 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='boatbuilder')
            UNION ALL SELECT osm_id, 158 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='bookbinder')
            UNION ALL SELECT osm_id, 159 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='carpenter')
            UNION ALL SELECT osm_id, 160 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='carpet_layer')
            UNION ALL SELECT osm_id, 161 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='caterer')
            UNION ALL SELECT osm_id, 162 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='clockmaker')
            UNION ALL SELECT osm_id, 163 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='dressmaker')
            UNION ALL SELECT osm_id, 164 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='electrician')
            UNION ALL SELECT osm_id, 165 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='gardener')
            UNION ALL SELECT osm_id, 166 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='glaziery')
            UNION ALL SELECT osm_id, 167 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='handicraft')
            UNION ALL SELECT osm_id, 168 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='hvac')
            UNION ALL SELECT osm_id, 169 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='insulation')
            UNION ALL SELECT osm_id, 170 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='jeweller')
            UNION ALL SELECT osm_id, 171 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='locksmith')
            UNION ALL SELECT osm_id, 172 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='key_cutter')
            UNION ALL SELECT osm_id, 173 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='metal_construction')
            UNION ALL SELECT osm_id, 174 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='optician')
            UNION ALL SELECT osm_id, 175 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='painter')
            UNION ALL SELECT osm_id, 176 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='parquet_layer')
            UNION ALL SELECT osm_id, 177 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='photographer')
            UNION ALL SELECT osm_id, 178 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='photographic_laboratory')
            UNION ALL SELECT osm_id, 179 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='plasterer')
            UNION ALL SELECT osm_id, 180 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='plumber')
            UNION ALL SELECT osm_id, 181 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='pottery')
            UNION ALL SELECT osm_id, 182 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='rigger')
            UNION ALL SELECT osm_id, 183 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='roofer')
            UNION ALL SELECT osm_id, 184 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='saddler')
            UNION ALL SELECT osm_id, 185 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='sailmaker')
            UNION ALL SELECT osm_id, 186 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='sawmill')
            UNION ALL SELECT osm_id, 187 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='scaffolder')
            UNION ALL SELECT osm_id, 188 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='sculptor')
            UNION ALL SELECT osm_id, 189 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='shoemaker')
            UNION ALL SELECT osm_id, 190 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='stand_builder')
            UNION ALL SELECT osm_id, 191 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='stonemason')
            UNION ALL SELECT osm_id, 192 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='sun_protection')
            UNION ALL SELECT osm_id, 193 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='sweep')
            UNION ALL SELECT osm_id, 194 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='tailor')
            UNION ALL SELECT osm_id, 195 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='tiler')
            UNION ALL SELECT osm_id, 196 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='tinsmith')
            UNION ALL SELECT osm_id, 197 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='upholsterer')
            UNION ALL SELECT osm_id, 198 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='watchmaker')
            UNION ALL SELECT osm_id, 199 AS category_id FROM :scm.osm_point_poi WHERE ("craft"='window_construction')
            UNION ALL SELECT osm_id, 200 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='bus_station')
            UNION ALL SELECT osm_id, 201 AS category_id FROM :scm.osm_point_poi WHERE ("railway"='subway_entrance')
            UNION ALL SELECT osm_id, 202 AS category_id FROM :scm.osm_point_poi WHERE ("railway"='station')
            UNION ALL SELECT osm_id, 203 AS category_id FROM :scm.osm_point_poi WHERE ("railway"='halt')
            UNION ALL SELECT osm_id, 204 AS category_id FROM :scm.osm_point_poi WHERE ("railway"='station' AND "station"='subway')
            UNION ALL SELECT osm_id, 205 AS category_id FROM :scm.osm_point_poi WHERE ("highway"='bus_stop')
            UNION ALL SELECT osm_id, 206 AS category_id FROM :scm.osm_point_poi WHERE ("railway"='tram_stop')
            UNION ALL SELECT osm_id, 207 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='taxi')
            UNION ALL SELECT osm_id, 208 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='car_repair')
            UNION ALL SELECT osm_id, 209 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='car_repair' AND "service"='tyres')
            UNION ALL SELECT osm_id, 210 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='vehicle_inspection')
            UNION ALL SELECT osm_id, 211 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='car_wash')
            UNION ALL SELECT osm_id, 212 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='fuel')
            UNION ALL SELECT osm_id, 213 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='charging_station')
            UNION ALL SELECT osm_id, 214 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='vehicle_ramp')
            UNION ALL SELECT osm_id, 215 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='school')
            UNION ALL SELECT osm_id, 216 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='kindergarten')
            UNION ALL SELECT osm_id, 217 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='library')
            UNION ALL SELECT osm_id, 218 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='college')
            UNION ALL SELECT osm_id, 219 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='university')
            UNION ALL SELECT osm_id, 220 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='arts_centre')
            UNION ALL SELECT osm_id, 221 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='cinema')
            UNION ALL SELECT osm_id, 222 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='nightclub')
            UNION ALL SELECT osm_id, 223 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='community_centre')
            UNION ALL SELECT osm_id, 224 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='theatre')
            UNION ALL SELECT osm_id, 225 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='theatre' AND "theatre:genre"='circus')
            UNION ALL SELECT osm_id, 226 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='place_of_worship')
            UNION ALL SELECT osm_id, 227 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='place_of_worship' AND "religion"='christian')
            UNION ALL SELECT osm_id, 228 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='place_of_worship' AND "religion"='jewish')
            UNION ALL SELECT osm_id, 229 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='place_of_worship' AND "religion"='muslim')
            UNION ALL SELECT osm_id, 230 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='monastery')
            UNION ALL SELECT osm_id, 231 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='police')
            UNION ALL SELECT osm_id, 232 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='courthouse')
            UNION ALL SELECT osm_id, 233 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='prison')
            UNION ALL SELECT osm_id, 234 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='register_office')
            UNION ALL SELECT osm_id, 235 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='embassy')
            UNION ALL SELECT osm_id, 236 AS category_id FROM :scm.osm_point_poi WHERE ("leisure"='stadium')
            UNION ALL SELECT osm_id, 237 AS category_id FROM :scm.osm_point_poi WHERE ("leisure"='sports_centre')
            UNION ALL SELECT osm_id, 238 AS category_id FROM :scm.osm_point_poi WHERE ("tourism"='museum')
            UNION ALL SELECT osm_id, 239 AS category_id FROM :scm.osm_point_poi WHERE ("tourism"='attraction')
            UNION ALL SELECT osm_id, 240 AS category_id FROM :scm.osm_point_poi WHERE ("tourism"='information')
            UNION ALL SELECT osm_id, 241 AS category_id FROM :scm.osm_point_poi WHERE ("historic"='memorial')
            UNION ALL SELECT osm_id, 242 AS category_id FROM :scm.osm_point_poi WHERE ("tourism"='artwork')
            UNION ALL SELECT osm_id, 243 AS category_id FROM :scm.osm_point_poi WHERE ("historic"='archaeological_site')
            UNION ALL SELECT osm_id, 244 AS category_id FROM :scm.osm_point_poi WHERE ("historic"='battlefield')
            UNION ALL SELECT osm_id, 245 AS category_id FROM :scm.osm_point_poi WHERE ("historic"='boundary_stone')
            UNION ALL SELECT osm_id, 246 AS category_id FROM :scm.osm_point_poi WHERE ("historic"='castle')
            UNION ALL SELECT osm_id, 247 AS category_id FROM :scm.osm_point_poi WHERE ("historic"='city_gate')
            UNION ALL SELECT osm_id, 248 AS category_id FROM :scm.osm_point_poi WHERE ("historic"='fort')
            UNION ALL SELECT osm_id, 249 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='fountain')
            UNION ALL SELECT osm_id, 250 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='clock')
            UNION ALL SELECT osm_id, 251 AS category_id FROM :scm.osm_point_poi WHERE ("historic"='ruins')
            UNION ALL SELECT osm_id, 252 AS category_id FROM :scm.osm_point_poi WHERE ("historic"='rune_stone')
            UNION ALL SELECT osm_id, 253 AS category_id FROM :scm.osm_point_poi WHERE ("historic"='wreck')
            UNION ALL SELECT osm_id, 254 AS category_id FROM :scm.osm_point_poi WHERE ("historic"='ship')
            UNION ALL SELECT osm_id, 255 AS category_id FROM :scm.osm_point_poi WHERE ("historic"='monument')
            UNION ALL SELECT osm_id, 256 AS category_id FROM :scm.osm_point_poi WHERE ("tourism"='hotel')
            UNION ALL SELECT osm_id, 257 AS category_id FROM :scm.osm_point_poi WHERE ("tourism"='guest_house')
            UNION ALL SELECT osm_id, 258 AS category_id FROM :scm.osm_point_poi WHERE ("tourism"='hostel')
            UNION ALL SELECT osm_id, 259 AS category_id FROM :scm.osm_point_poi WHERE ("tourism"='motel')
            UNION ALL SELECT osm_id, 260 AS category_id FROM :scm.osm_point_poi WHERE ("office"='company')
            UNION ALL SELECT osm_id, 261 AS category_id FROM :scm.osm_point_poi WHERE ("office"='government')
            UNION ALL SELECT osm_id, 262 AS category_id FROM :scm.osm_point_poi WHERE ("office"='government' AND "government"='bailiff')
            UNION ALL SELECT osm_id, 263 AS category_id FROM :scm.osm_point_poi WHERE ("office"='government' AND "government"='prosecutor')
            UNION ALL SELECT osm_id, 264 AS category_id FROM :scm.osm_point_poi WHERE ("office"='government' AND "government"='pension_fund')
            UNION ALL SELECT osm_id, 265 AS category_id FROM :scm.osm_point_poi WHERE ("office"='government' AND "government"='migration')
            UNION ALL SELECT osm_id, 266 AS category_id FROM :scm.osm_point_poi WHERE ("office"='government' AND "government"='taxes')
            UNION ALL SELECT osm_id, 267 AS category_id FROM :scm.osm_point_poi WHERE ("office"='insurance')
            UNION ALL SELECT osm_id, 268 AS category_id FROM :scm.osm_point_poi WHERE ("office"='estate_agent')
            UNION ALL SELECT osm_id, 269 AS category_id FROM :scm.osm_point_poi WHERE ("office"='lawyer')
            UNION ALL SELECT osm_id, 270 AS category_id FROM :scm.osm_point_poi WHERE ("office"='lawyer' AND "lawyer"='notary')
            UNION ALL SELECT osm_id, 271 AS category_id FROM :scm.osm_point_poi WHERE ("office"='telecommunication')
            UNION ALL SELECT osm_id, 272 AS category_id FROM :scm.osm_point_poi WHERE ("office"='travel_agent')
            UNION ALL SELECT osm_id, 273 AS category_id FROM :scm.osm_point_poi WHERE ("office"='ngo')
            UNION ALL SELECT osm_id, 274 AS category_id FROM :scm.osm_point_poi WHERE ("office"='administrative')
            UNION ALL SELECT osm_id, 275 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='townhall')
            UNION ALL SELECT osm_id, 276 AS category_id FROM :scm.osm_point_poi WHERE ("office"='accountant')
            UNION ALL SELECT osm_id, 277 AS category_id FROM :scm.osm_point_poi WHERE ("office"='employment_agency')
            UNION ALL SELECT osm_id, 278 AS category_id FROM :scm.osm_point_poi WHERE ("office"='research')
            UNION ALL SELECT osm_id, 279 AS category_id FROM :scm.osm_point_poi WHERE ("office"='it')
            UNION ALL SELECT osm_id, 280 AS category_id FROM :scm.osm_point_poi WHERE ("office"='newspaper')
            UNION ALL SELECT osm_id, 281 AS category_id FROM :scm.osm_point_poi WHERE ("office"='architect')
            UNION ALL SELECT osm_id, 282 AS category_id FROM :scm.osm_point_poi WHERE ("office"='advertising_agency')
            UNION ALL SELECT osm_id, 283 AS category_id FROM :scm.osm_point_poi WHERE ("office"='educational_institution')
            UNION ALL SELECT osm_id, 284 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='studio')
            UNION ALL SELECT osm_id, 285 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='bookmaker')
            UNION ALL SELECT osm_id, 286 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='toilets')
            UNION ALL SELECT osm_id, 287 AS category_id FROM :scm.osm_point_poi WHERE ("tourism"='viewpoint')
            UNION ALL SELECT osm_id, 288 AS category_id FROM :scm.osm_point_poi WHERE ("tourism"='camp_site')
            UNION ALL SELECT osm_id, 289 AS category_id FROM :scm.osm_point_poi WHERE ("tourism"='picnic_site')
            UNION ALL SELECT osm_id, 290 AS category_id FROM :scm.osm_point_poi WHERE ("natural"='cave_entrance')
            UNION ALL SELECT osm_id, 291 AS category_id FROM :scm.osm_point_poi WHERE ("natural"='peak')
            UNION ALL SELECT osm_id, 292 AS category_id FROM :scm.osm_point_poi WHERE ("natural"='rock' OR "natural"='bare_rock' OR "natural"='cliff')
            UNION ALL SELECT osm_id, 293 AS category_id FROM :scm.osm_point_poi WHERE ("natural"='volcano')
            UNION ALL SELECT osm_id, 294 AS category_id FROM :scm.osm_point_poi WHERE ("natural"='waterfall' OR "waterway"='waterfall')
            UNION ALL SELECT osm_id, 295 AS category_id FROM :scm.osm_point_poi WHERE ("natural"='spring')
            UNION ALL SELECT osm_id, 296 AS category_id FROM :scm.osm_point_poi WHERE ("natural"='cape')
            UNION ALL SELECT osm_id, 297 AS category_id FROM :scm.osm_point_poi WHERE ("natural"='bay')
            UNION ALL SELECT osm_id, 298 AS category_id FROM :scm.osm_point_poi WHERE ("natural"='strait')
            UNION ALL SELECT osm_id, 302 AS category_id FROM :scm.osm_point_poi WHERE ("leisure"='beach_resort')
            UNION ALL SELECT osm_id, 303 AS category_id FROM :scm.osm_point_poi WHERE ("leisure"='dance')
            UNION ALL SELECT osm_id, 304 AS category_id FROM :scm.osm_point_poi WHERE ("leisure"='dog_park')
            UNION ALL SELECT osm_id, 305 AS category_id FROM :scm.osm_point_poi WHERE ("leisure"='fishing')
            UNION ALL SELECT osm_id, 306 AS category_id FROM :scm.osm_point_poi WHERE ("leisure"='golf_course')
            UNION ALL SELECT osm_id, 307 AS category_id FROM :scm.osm_point_poi WHERE ("leisure"='ice_rink')
            UNION ALL SELECT osm_id, 308 AS category_id FROM :scm.osm_point_poi WHERE ("leisure"='marina')
            UNION ALL SELECT osm_id, 309 AS category_id FROM :scm.osm_point_poi WHERE ("leisure"='slipway')
            UNION ALL SELECT osm_id, 310 AS category_id FROM :scm.osm_point_poi WHERE ("leisure"='miniature_golf')
            UNION ALL SELECT osm_id, 311 AS category_id FROM :scm.osm_point_poi WHERE ("leisure"='pitch')
            UNION ALL SELECT osm_id, 312 AS category_id FROM :scm.osm_point_poi WHERE ("leisure"='track' AND "sport"='running')
            UNION ALL SELECT osm_id, 313 AS category_id FROM :scm.osm_point_poi WHERE ("leisure"='track' AND "sport"='cycling')
            UNION ALL SELECT osm_id, 314 AS category_id FROM :scm.osm_point_poi WHERE ("leisure"='track' AND "sport"='horse_racing')
            UNION ALL SELECT osm_id, 316 AS category_id FROM :scm.osm_point_poi WHERE ("leisure"='playground')
            UNION ALL SELECT osm_id, 317 AS category_id FROM :scm.osm_point_poi WHERE ("leisure"='swimming_pool')
            UNION ALL SELECT osm_id, 318 AS category_id FROM :scm.osm_point_poi WHERE ("leisure"='water_park')
            UNION ALL SELECT osm_id, 319 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='cosmetics')
            UNION ALL SELECT osm_id, 320 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='marketplace')
            UNION ALL SELECT osm_id, 321 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='telephone')
            UNION ALL SELECT osm_id, 322 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='ferry_terminal')
            UNION ALL SELECT osm_id, 323 AS category_id FROM :scm.osm_point_poi WHERE ("landuse"='cemetery')
            UNION ALL SELECT osm_id, 324 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='fire_station')
            UNION ALL SELECT osm_id, 325 AS category_id FROM :scm.osm_point_poi WHERE ("emergency"='phone')
            UNION ALL SELECT osm_id, 326 AS category_id FROM :scm.osm_point_poi WHERE ("emergency"='fire_hydrant')
            UNION ALL SELECT osm_id, 327 AS category_id FROM :scm.osm_point_poi WHERE ("emergency"='fire_water_pond')
            UNION ALL SELECT osm_id, 328 AS category_id FROM :scm.osm_point_poi WHERE ("emergency"='ambulance_station')
            UNION ALL SELECT osm_id, 329 AS category_id FROM :scm.osm_point_poi WHERE ("leisure"='park')
            UNION ALL SELECT osm_id, 330 AS category_id FROM :scm.osm_point_poi WHERE ("aeroway"='aerodrome')
            UNION ALL SELECT osm_id, 331 AS category_id FROM :scm.osm_point_poi WHERE ("aeroway"='helipad')
            UNION ALL SELECT osm_id, 332 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='shelter')
            UNION ALL SELECT osm_id, 333 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='drinking_water')
            UNION ALL SELECT osm_id, 334 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='sauna')
            UNION ALL SELECT osm_id, 335 AS category_id FROM :scm.osm_point_poi WHERE ("tourism"='zoo')
            UNION ALL SELECT osm_id, 336 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='parking')
            UNION ALL SELECT osm_id, 337 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='parking_entrance')
            UNION ALL SELECT osm_id, 338 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='bicycle_parking')
            UNION ALL SELECT osm_id, 339 AS category_id FROM :scm.osm_point_poi WHERE ("tourism"='theme_park')
            UNION ALL SELECT osm_id, 340 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='customs')
            UNION ALL SELECT osm_id, 341 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='recycling')
            UNION ALL SELECT osm_id, 342 AS category_id FROM :scm.osm_point_poi WHERE ("ford"='yes')
            UNION ALL SELECT osm_id, 343 AS category_id FROM :scm.osm_point_poi WHERE ("mountain_pass"='yes')
            UNION ALL SELECT osm_id, 344 AS category_id FROM :scm.osm_point_poi WHERE ("barrier"='gate')
            UNION ALL SELECT osm_id, 345 AS category_id FROM :scm.osm_point_poi WHERE ("barrier"='lift_gate')
            UNION ALL SELECT osm_id, 346 AS category_id FROM :scm.osm_point_poi WHERE ("barrier"='toll_booth')
            UNION ALL SELECT osm_id, 347 AS category_id FROM :scm.osm_point_poi WHERE ("traffic_calming"='bump')
            UNION ALL SELECT osm_id, 348 AS category_id FROM :scm.osm_point_poi WHERE ("traffic_calming"='hump')
            UNION ALL SELECT osm_id, 349 AS category_id FROM :scm.osm_point_poi WHERE ("traffic_calming"='cushion')
            UNION ALL SELECT osm_id, 350 AS category_id FROM :scm.osm_point_poi WHERE ("highway"='traffic_signals')
            UNION ALL SELECT osm_id, 351 AS category_id FROM :scm.osm_point_poi WHERE ("man_made"='surveillance')
            UNION ALL SELECT osm_id, 352 AS category_id FROM :scm.osm_point_poi WHERE ("man_made"='tower' AND "tower:type"='communication')
            UNION ALL SELECT osm_id, 353 AS category_id FROM :scm.osm_point_poi WHERE ("man_made"='telephone_exchange')
            UNION ALL SELECT osm_id, 354 AS category_id FROM :scm.osm_point_poi WHERE ("man_made"='water_well')
            UNION ALL SELECT osm_id, 355 AS category_id FROM :scm.osm_point_poi WHERE ("man_made"='standpipe')
            UNION ALL SELECT osm_id, 356 AS category_id FROM :scm.osm_point_poi WHERE ("man_made"='water_works')
            UNION ALL SELECT osm_id, 357 AS category_id FROM :scm.osm_point_poi WHERE ("man_made"='wastewater_plant')
            UNION ALL SELECT osm_id, 358 AS category_id FROM :scm.osm_point_poi WHERE ("man_made"='water_tower')
            UNION ALL SELECT osm_id, 359 AS category_id FROM :scm.osm_point_poi WHERE ("power"='substation' OR "power"='station')
            UNION ALL SELECT osm_id, 360 AS category_id FROM :scm.osm_point_poi WHERE ("power"='transformer')
            UNION ALL SELECT osm_id, 361 AS category_id FROM :scm.osm_point_poi WHERE ("power"='plant' AND "plant:output:electricity"='*')
            UNION ALL SELECT osm_id, 362 AS category_id FROM :scm.osm_point_poi WHERE ("power"='generator' AND "generator:output:electricity"='*')
            UNION ALL SELECT osm_id, 363 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='sewing')
            UNION ALL SELECT osm_id, 364 AS category_id FROM :scm.osm_point_poi WHERE ("seamark:type"='beacon_special_purpose' AND "seamark:beacon_special_purpose:category"='leading')
            UNION ALL SELECT osm_id, 365 AS category_id FROM :scm.osm_point_poi WHERE ("seamark:type"='buoy_lateral')
            UNION ALL SELECT osm_id, 366 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='internet_cafe')
            UNION ALL SELECT osm_id, 367 AS category_id FROM :scm.osm_point_poi WHERE ("club"='art')
            UNION ALL SELECT osm_id, 368 AS category_id FROM :scm.osm_point_poi WHERE ("club"='astronomy')
            UNION ALL SELECT osm_id, 369 AS category_id FROM :scm.osm_point_poi WHERE ("club"='computer')
            UNION ALL SELECT osm_id, 370 AS category_id FROM :scm.osm_point_poi WHERE ("club"='board_games')
            UNION ALL SELECT osm_id, 371 AS category_id FROM :scm.osm_point_poi WHERE ("club"='motorcycle')
            UNION ALL SELECT osm_id, 372 AS category_id FROM :scm.osm_point_poi WHERE ("club"='sport')
            UNION ALL SELECT osm_id, 373 AS category_id FROM :scm.osm_point_poi WHERE ("club"='game')
            UNION ALL SELECT osm_id, 374 AS category_id FROM :scm.osm_point_poi WHERE ("club"='automobile')
            UNION ALL SELECT osm_id, 375 AS category_id FROM :scm.osm_point_poi WHERE ("club"='chess')
            UNION ALL SELECT osm_id, 376 AS category_id FROM :scm.osm_point_poi WHERE ("club"='cinema')
            UNION ALL SELECT osm_id, 377 AS category_id FROM :scm.osm_point_poi WHERE ("club"='fan')
            UNION ALL SELECT osm_id, 378 AS category_id FROM :scm.osm_point_poi WHERE ("club"='fishing')
            UNION ALL SELECT osm_id, 379 AS category_id FROM :scm.osm_point_poi WHERE ("club"='veterans')
            UNION ALL SELECT osm_id, 380 AS category_id FROM :scm.osm_point_poi WHERE ("club"='linux')
            UNION ALL SELECT osm_id, 381 AS category_id FROM :scm.osm_point_poi WHERE ("club"='theatre')
            UNION ALL SELECT osm_id, 382 AS category_id FROM :scm.osm_point_poi WHERE ("club"='history')
            UNION ALL SELECT osm_id, 383 AS category_id FROM :scm.osm_point_poi WHERE ("club"='music')
            UNION ALL SELECT osm_id, 384 AS category_id FROM :scm.osm_point_poi WHERE ("club"='ethnic')
            UNION ALL SELECT osm_id, 385 AS category_id FROM :scm.osm_point_poi WHERE ("club"='nature')
            UNION ALL SELECT osm_id, 386 AS category_id FROM :scm.osm_point_poi WHERE ("club"='photography')
            UNION ALL SELECT osm_id, 387 AS category_id FROM :scm.osm_point_poi WHERE ("club"='hunting')
            UNION ALL SELECT osm_id, 388 AS category_id FROM :scm.osm_point_poi WHERE ("club"='shooting')
            UNION ALL SELECT osm_id, 389 AS category_id FROM :scm.osm_point_poi WHERE ("club"='tourism')
            UNION ALL SELECT osm_id, 390 AS category_id FROM :scm.osm_point_poi WHERE ("club"='charity')
            UNION ALL SELECT osm_id, 391 AS category_id FROM :scm.osm_point_poi WHERE ("man_made"='tunnel')
            UNION ALL SELECT osm_id, 392 AS category_id FROM :scm.osm_point_poi WHERE ("man_made"='bridge')
            UNION ALL SELECT osm_id, 393 AS category_id FROM :scm.osm_point_poi WHERE ("landuse"='construction')
            UNION ALL SELECT osm_id, 394 AS category_id FROM :scm.osm_point_poi WHERE ("landuse"='landfill')
            UNION ALL SELECT osm_id, 395 AS category_id FROM :scm.osm_point_poi WHERE ("amenity"='waste_disposal')
            UNION ALL SELECT osm_id, 396 AS category_id FROM :scm.osm_point_poi WHERE ("landuse"='garages')
            UNION ALL SELECT osm_id, 397 AS category_id FROM :scm.osm_point_poi WHERE ("man_made"='lighthouse')
            UNION ALL SELECT osm_id, 398 AS category_id FROM :scm.osm_point_poi WHERE ("highway"='speed_camera')
            UNION ALL SELECT osm_id, 399 AS category_id FROM :scm.osm_point_poi WHERE ("railway"='funicular')
            UNION ALL SELECT osm_id, 400 AS category_id FROM :scm.osm_point_poi WHERE ("shop"='tea')
            UNION ALL SELECT osm_id, 401 AS category_id FROM :scm.osm_point_poi WHERE ("advertising"='billboard')
            UNION ALL SELECT osm_id, 402 AS category_id FROM :scm.osm_point_poi WHERE ("advertising"='column')
            UNION ALL SELECT osm_id, 403 AS category_id FROM :scm.osm_point_poi WHERE ("advertising"='flag')
            UNION ALL SELECT osm_id, 404 AS category_id FROM :scm.osm_point_poi WHERE ("advertising"='sign')
            UNION ALL SELECT osm_id, 405 AS category_id FROM :scm.osm_point_poi WHERE ("advertising"='screen')
            UNION ALL SELECT osm_id, 406 AS category_id FROM :scm.osm_point_poi WHERE ("advertising"='culpture')
            UNION ALL SELECT osm_id, 407 AS category_id FROM :scm.osm_point_poi WHERE ("advertising"='wall_painting')      
      ) AS foo
    GROUP BY osm_id
    ) AS u2
    INNER JOIN :scm.osm_point_poi ON :scm.osm_point_poi.osm_id = u2.osm_id
UNION ALL
SELECT u3.osm_id, name, name_uk, name_ru, name_pl, name_en, addr_housenumber, addr_street, addr_suburb, operator, phone, contact_phone, website, contact_website, email, contact_email, fax, contact_fax, wikipedia, opening_hours,
category_id,
geometry AS boundary, centre,
1 AS type, lat, lon
FROM
    (SELECT osm_id, array_agg(category_id) AS category_id FROM (
            SELECT osm_id, 242 AS category_id FROM :scm.osm_linestring_poi WHERE ("tourism"='artwork')
            UNION ALL SELECT osm_id, 250 AS category_id FROM :scm.osm_linestring_poi WHERE ("amenity"='clock')
            UNION ALL SELECT osm_id, 298 AS category_id FROM :scm.osm_linestring_poi WHERE ("natural"='strait')
            UNION ALL SELECT osm_id, 312 AS category_id FROM :scm.osm_linestring_poi WHERE ("leisure"='track' AND "sport"='running')
            UNION ALL SELECT osm_id, 313 AS category_id FROM :scm.osm_linestring_poi WHERE ("leisure"='track' AND "sport"='cycling')
            UNION ALL SELECT osm_id, 314 AS category_id FROM :scm.osm_linestring_poi WHERE ("leisure"='track' AND "sport"='horse_racing')
            UNION ALL SELECT osm_id, 315 AS category_id FROM :scm.osm_linestring_poi WHERE ("highway"='raceway')
            UNION ALL SELECT osm_id, 342 AS category_id FROM :scm.osm_linestring_poi WHERE ("ford"='yes')
            UNION ALL SELECT osm_id, 343 AS category_id FROM :scm.osm_linestring_poi WHERE ("mountain_pass"='yes')
            UNION ALL SELECT osm_id, 399 AS category_id FROM :scm.osm_linestring_poi WHERE ("railway"='funicular')
            UNION ALL SELECT osm_id, 400 AS category_id FROM :scm.osm_linestring_poi WHERE ("shop"='tea')
            UNION ALL SELECT osm_id, 401 AS category_id FROM :scm.osm_linestring_poi WHERE ("advertising"='billboard')
            UNION ALL SELECT osm_id, 404 AS category_id FROM :scm.osm_linestring_poi WHERE ("advertising"='sign')
            UNION ALL SELECT osm_id, 405 AS category_id FROM :scm.osm_linestring_poi WHERE ("advertising"='screen')
            UNION ALL SELECT osm_id, 406 AS category_id FROM :scm.osm_linestring_poi WHERE ("advertising"='culpture')
            UNION ALL SELECT osm_id, 407 AS category_id FROM :scm.osm_linestring_poi WHERE ("advertising"='wall_painting')
      
      ) AS foo
    GROUP BY osm_id
    ) AS u3
    INNER JOIN :scm.osm_linestring_poi ON :scm.osm_linestring_poi.osm_id = u3.osm_id
) AS bar;

DROP TABLE IF EXISTS import.osm_poi CASCADE;

CREATE TABLE import.osm_poi AS SELECT * FROM import.osm_poi_view;
  
ALTER TABLE import.osm_poi ADD PRIMARY KEY (id);


\echo '\nPOI: Create spatial indexes'
CREATE INDEX osm_poi_centre ON import.osm_poi USING GIST(centre);
--CLUSTER osm_poi_centre ON import.osm_poi;
--ALTER TABLE import.osm_poi ADD CONSTRAINT enforce_dims_centre CHECK (st_ndims(centre) = 2);
--ALTER TABLE import.osm_poi ADD CONSTRAINT enforce_geotype_centre CHECK (geometrytype(centre) = 'POINT'::text OR centre IS NULL);
--ALTER TABLE import.osm_poi ADD CONSTRAINT enforce_srid_centre CHECK (st_srid(centre) = 3857);

CREATE INDEX osm_poi_boundary ON import.osm_poi USING GIST(boundary);
CREATE INDEX osm_poi_geom_geohash ON import.osm_poi (ST_GeoHash(ST_Transform(ST_SetSRID(Box2D(boundary), 3857), 4326)));
CLUSTER osm_places_geom_geohash ON import.osm_places;
--CLUSTER osm_poi_boundary ON import.osm_poi;
--ALTER TABLE import.osm_poi ADD CONSTRAINT enforce_dims_boundary CHECK (st_ndims(boundary) = 2);
--ALTER TABLE import.osm_poi ADD CONSTRAINT enforce_srid_boundary CHECK (st_srid(boundary) = 3857);

DROP VIEW IF EXISTS import.osm_poi_view CASCADE;


CREATE INDEX osm_poi_osm_id_idx ON import.osm_poi USING BTREE(osm_id);

\echo '\nPOI: Add place_id'
ALTER TABLE import.osm_poi
      ADD COLUMN place_id bigint,
      ADD COLUMN street_id int,

      ADD COLUMN state_id bigint,
      ADD COLUMN country_code character(2);

ANALYZE import.osm_poi;

\echo '\nPOI: Link to Places'
UPDATE import.osm_poi p SET
      place_id = c.osm_id,
      country_code = c.country_code,
      state_id = c.state_id
FROM :scm.osm_places c WHERE ST_Contains(c.boundary, p.centre);

CREATE INDEX osm_poi_place_id_idx ON :scm.osm_poi USING BTREE (place_id);
ANALYZE import.osm_poi; 

\echo '\nPOI: Delete nested'
/*
DELETE FROM import.osm_poi WHERE id IN (
SELECT o2.id
FROM import.osm_poi o1
INNER JOIN import.osm_poi o2 ON o1.osm_id <> o2.osm_id AND o1.type = 2 AND o1.type = o2.type AND o1.place_id = o2.place_id AND o1.category_id = o2.category_id AND ST_Contains(o2.boundary, o1.boundary)
);
*/

DELETE FROM import.osm_poi d
USING (SELECT o2.id
FROM import.osm_poi o1
INNER JOIN import.osm_poi o2 ON o1.osm_id <> o2.osm_id AND o1.type = 2 AND o2.type = 2 AND o1.place_id = o2.place_id AND o1.category_id = o2.category_id AND ST_Contains(o2.boundary, o1.boundary)
) AS sub
WHERE d.id = sub.id;

\echo '\nPOI: Link to States'
UPDATE import.osm_poi p SET state_id = a.osm_id, country_code = a.country_code
FROM :scm.osm_admin a
WHERE place_id IS NULL AND a.level = 2
AND ST_Contains(a.boundary, p.centre);


CREATE INDEX osm_poi_addr_suburb_idx ON import.osm_poi(addr_suburb);
CREATE INDEX osm_poi_addr_street_idx ON import.osm_poi(addr_street);
ANALYZE import.osm_poi;

\echo '\nPOI: Link to Streets (addr)'
UPDATE import.osm_poi p SET street_id = s.id FROM :scm.osm_streets s WHERE p.place_id = s.place_id AND p.addr_suburb = s.addr_suburb AND p.addr_street = s.name;

\echo '\nPOI: Link to Streets (building)'
UPDATE import.osm_poi p SET street_id = b.street_id, addr_housenumber = b.addr_housenumber FROM :scm.osm_buildings b WHERE p.type = 0 AND b.street_id IS NOT NULL AND (ST_Contains(b.geometry, p.centre) OR ST_Touches(p.centre, b.geometry));

\echo '\nPOI: Link to Streets (building=POI)'
UPDATE import.osm_poi p SET street_id = b.street_id FROM :scm.osm_buildings b WHERE p.boundary IS NOT NULL AND b.street_id IS NOT NULL AND p.osm_id = b.osm_id;
